#!/usr/bin/env python3

# Modules
import argparse
import subprocess
import sys
import os
import datetime

# Function to check inputs
def check_empty_or_integer(value):
	if value == "":
		return(value)
	else:
		if value.isdigit():
			return(value)
		else:
			sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... '"+value+"' should be an integer.")

# Manage inputs
parser  = argparse.ArgumentParser(prog='IgCaller', description='''IgCaller v2.0 (https://github.com/ferrannadeu/IgCaller)''')

parser.add_argument('-v', '--version', action='version', version="%(prog)s v2.0")

# Mandatory:
parser.add_argument('-I', '--inputsFolder',
					dest = "inputsFolder",
					action = "store",
					required = True,
					help = "Path to folder containing IgCaller reference files.") 

parser.add_argument('-V', '--genomeVersion',
					dest = "genomeVersion",
					action = "store",
					choices = ['hg19', 'hg38'],
					required = True,
					help = "Reference genome version [hg19, hg38].") 

parser.add_argument('-C', '--chromosomeAnnotation',
					dest = "chrAnnot",
					action = "store",
					choices = ['ensembl', 'ucsc'],
					required = True,
					help = "Chromosome annotation [ensembl = without 'chr' (i.e. 1); ucsc = with 'chr' (i.e. chr1)].") 

parser.add_argument('-T', '--bamT',
					dest = "bamT",
					action = "store",
					required = True,
					help = "Path to tumor BAM file.") 

parser.add_argument('-seq', '--sequencing', 
					dest = "seq",
					action = "store",
					required = True,
					choices = ['wgs', 'wes', 'capture', 'amplicon'],
					help = "Sequencing technique [whole-genome sequencing (wgs), whole-exome sequencing (wes), high-coverage capture NGS (capture), or amplicon-based NGS (amplicon)].")

parser.add_argument('-seqDepth', '--sequencingDepth', 
					dest = "seqDepth",
					action = "store",
					required = True,
					choices = ['low', 'int', 'high'],
					help = "Sequencing depth [low (~30x), int (50-200x), high (>250x)].")

parser.add_argument('-N', '--bamN',
					dest = "bamN",
					action = "store",
					default = None,
					help = "Path to normal BAM file, if available.") 

parser.add_argument('-pm', '--pairedMode',
					dest = "pairedMode",
					action = "store",
					default = None,
					choices = ['paired', 'unpaired'],
					help = "Tumor and normal paired status [paired/unpaired, default=None]. Need to be specified when bamN is specified. Paired = Normal BAM used for all analyses. Unpaired = Normal BAM only used during the estimation of tumor purity based on coverage.") 

parser.add_argument('-R', '--refGenome',
					dest = "refGenome",
					action = "store",
					default = None,
					help = "Path to reference genome FASTA file. Not mandatory, but recommended, when specifying a normal BAM file using the argument 'bamN'. Mandatory when '-bamN' is not specified and when '-seq' is set to 'amplicon'.") 

# Gene/receptor to be analyzed:
parser.add_argument('-g', '--geneToAnalyze',
					dest = "geneToAnalyze",
					action = "store",
					choices = ['ig', 'tcr', 'both'],
					default = "ig",
					help = "Gene/receptor to be analyzed [ig/tcr/both, default=ig].") 

# Amplicon-based sequencing:
parser.add_argument('-pr', '--primer',
					dest = "primer",
					action = "store",
					default = None,
					choices = ['leader', 'fr1', 'cdr1', 'fr2', 'cdr2', 'fr3', 'Vseq'],
					help = "Location of the primer in the V gene for amplicon-based data [leader/fr1/cdr1/fr2/cdr2/fr3/Vseq, default=None]. It is used to cut the sequence after the primer location (if leader, fr1, cdr1, fr2, cdr2, fr3) or sequence (if Vseq) prior annotation and identity calculation. Only applicable when IgBLAST is used for the annotation using the '-a' argument. Required if '-seq amplicon'. See parameter '--primerStringency' and 'primerFasta' for further tunning.")

parser.add_argument('-prf', '--primerFasta',
					dest = "primerFasta",
					action = "store",
					default = "",
					help = "Fasta file with primer sequences annealing to V genes that need to be removed from the sequence. Mandatory when '-pr/--primer' is 'Vseq'. Sequence name (or header line) in fasta file must start with '>locus', where locus is IGH, IGK, IGL, TRA, TRAB, TRAG, or TRAD to allow locus-specific mapping and elimination of primers. Only applicable when IgBLAST is used for the annotation using the '-a' argument (recommended).")

parser.add_argument('-prs', '--primerStringency',
					dest = "primerStringency",
					action = "store",
					default = "strict",
					choices = ['strict', 'permissive'],
					help = "Primer stringency [strict/permissive, default=strict]. Mandatory when '-pr/--primer' is 'leader', 'fr1', 'cdr1', 'fr2', 'cdr2', or 'fr3'. 'strict' = only annotate sequences with nucleotides found after the expected location of the primer. 'permissive' = annotate sequences even if they start later than the expected location of the primer. Only applicable when IgBLAST is used for the annotation using the '-a' argument (recommended).")

# Purity of the tumor sample:
parser.add_argument('-p', '--tumorPurity', 
					dest = "tumorPurity",
					action = "store",
					default = "1",
					type = float,
					help = "Purity (or tumor cell contect) of the tumor sample, if known [0-1, default=1]. It is used to adjust the scores and some internal cutoffs during the analysis. If unknown, use 1.") 

# Output path and options:
parser.add_argument('-o', '--outputPath',
					dest = "outputPath",
					action = "store",
					default = None,
					help = "A folder inside this directory will be created with the output [default = current directory].") 

parser.add_argument('-kmb', '--keepMiniIgBams',
					dest = "keepMiniIgBams",
					action = "store",
					default = "no",
					help = "Should IgCaller keep (ie no remove) mini IG BAM files used in the analysis? [no/yes, default=no].")

parser.add_argument('-rrn', '--reportReadNames', 
					dest = "reportReadNames",
					action = "store",
					default = "no",
					choices = ['no', 'yes'],
					help = "Report read names associated with each rearrangement found [no/yes, default=no].")

# Annotation tool and database:
parser.add_argument('-a', '--annotateSeq',
					dest = "annotateSeq",
					action = "store",
					default = "igblast",
					choices = ['builtin', 'igblast'],
					help = "Annotate sequence using IgCaller built-in annotation workflow or using IgBLAST [builtin/igblast, default=igblast].") 

parser.add_argument('-aa', '--annotateSeqDB',
					dest = "annotateSeqDB",
					action = "store",
					default = "imgt",
					choices = ['imgt', 'ogrdb'],
					help = "Database of sequences to be used by IgBLAST [imgt/ogrdb, default=imgt]. IMGT = release 202430-2 (23 July 2024); OGRDB = release 2024-10-12.") 

# CLL-specific annotations:
parser.add_argument('-subsets', '--subsetsAnnotation', 
					dest = "subsetsAnnotation",
					action = "store",
					default = "no",
					choices = ['no', 'imgt', 'major'],
					help = "Should CLL stereotype subsets be annotated? Only applicable to productive IGH gene rearrangements. 'imgt' to annotate #2 and #8 using IMGT criteria; 'major' to annotate all major subsets based on the definitions reported in Agathangelidis et al Blood 2021 [no/imgt/major, default = no].")

parser.add_argument('-R110', '--R110annotation', 
					dest = "R110annotation",
					action = "store",
					default = "no",
					choices = ['no', 'yes'],
					help = "Should the R110 mutation in IGLV3-21 be annotated? Annotation based on the definitions reported in Nadeu et al Blood 2021 [no/yes, default = no].")

# Acquired N-glycosylation sites (AGS) annotation:
parser.add_argument('-ags', '--agsAnnotation',
					dest = "agsAnnotation",
					action = "store",
					default = "no",
					choices = ['no', 'yes'],
					help = "Should acquired N-glycosylation sites (AGS) be annotated? Only applicable to productive IGH gene rearrangements and requires '-a igblast'. AGS annotation based on the definitions reported in Tatterton et al Blood 2025 [no/yes, default = no].")

# IG/TCR reconstruction:
parser.add_argument('-hs', '--highSensitivity', 
					dest = "highSensitivity",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "highSensitivity = no: runs faster by skipping low-confidence rearrangements. highSensitivity = yes: may run significantly slower in some samples since it tries to recover low-confidence rearrangements [no/yes, default = yes].")

parser.add_argument('-mnns', '--minimumNumberOfNucleotidesSoft',
					dest = "minimumNumberOfNucleotidesSoft",
					action = "store",
					default = "5",
					type = int,
					help = "Minimum number of soft-clipped nucleotides to consider a read as split-read and number of nucleotides to be aligned on a J-V, J-D or D-V break in order to recover the read as a split-read covering the rearrangement [integer number higher than 0, default = 5].")

parser.add_argument('-prbm', '--phaseReadsBasedOnMutations', 
					dest = "phaseReadsBasedOnMutations",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Phase reads based on mutations identified in the V gene. They will be used to reconstruct the sequence on the V gene but not considered to calculate the score and mapping quality [no/yes, default = yes].")

parser.add_argument('-kisor', '--keepInsertSizeOnlyRearrangements', 
					dest = "keepInsertSizeOnlyRearrangements",
					action = "store",
					default = "no",
					choices = ['no', 'yes'],
					help = "Specify if IG/TCR rearrangements supported only by insert-size reads (i.e., no split-reads) should be kept [no/yes, default = no]. If kept, they are labeled with the tag 'Rearrangement without junction coverage' and the nucleotide sequences, functionality, identity to germline, and other features are not computed. If specified, these rearrangements are reported in the filtered output independently of the value specified in the '-rop' argument.")

parser.add_argument('-cs', '--collapseSequences', 
					dest = "collapseSequences",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Collapse IG/TCR sequences if they are similar at nucleotide level. If so, the sequence of the rearrangement supported with the highest score is kept, but number of reads and read names are merged in the output [no/yes, default = yes].")

parser.add_argument('-css', '--collapseSequencesSimilarity', 
					dest = "collapseSequencesSimilarity",
					action = "store",
					default = "0.98",
					type = float,
					help = "Cutoff of similarity between two IG/TCR sequences in order to be collapsed [0-1, default=0.98].")

parser.add_argument('-shortV', '--shortReportedVseq',
					dest = "shortV",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Make V sequence start at (approx) FR1 [yes/no, default=yes].")

parser.add_argument('-mq', '--mappingQuality',
					dest = "mapq",
					action = "store",
					default = "0",
					type = int,
					help = "Mapping quality cut off to filter out reads for IG/TCR V(D)J reconstruction [default=0].") 

parser.add_argument('-bq', '--baseQuality',
					dest = "baseq",
					action = "store",
					default = "13",
					type = int,
					help = "Base quality cut off for samtools mpileup for mutation analysis [default=13].") 

parser.add_argument('-d', '--minDepth',
					dest = "depth",
					action = "store",
					default = "1",
					type = int,
					help = "Depth cut off to consider a position [0-inf, default=1].")
					
parser.add_argument('-ad', '--minAltDepth',
					dest = "altDepth",
					action = "store",
					default = "1",
					type = int,
					help = "Alt depth cut off to consider a nucleotide [0-inf, default=1].")
					
parser.add_argument('-vaf', '--vafCutoff',
					dest = "vafCutoff",
					action = "store",
					default = "0.5,0.1",
					help = "VAF cut off to consider a mutation when working with phased reads and without phased reads, respectively [two numbers between 0-1 separated by comma, default=0.5,0.1].")	

parser.add_argument('-vafN', '--vafCutoffNormal',
					dest = "vafCutoffNormal",
					action = "store",
					default = "0.20",
					type = float,
					help = "VAF cut off to consider a variant in the normal sample [0-1, default=0.20].")

parser.add_argument('-s', '--scoreCutoff',
					dest = "scoreCutoff",
					action = "store",
					default = "",
					type = check_empty_or_integer,
					help = "Minimum score supporting a gene rearrangement in order to be considered as high confidence [default='empty'; will consider 5 for seqDepth = low, 10 for int, and 15 for high].")

parser.add_argument('-sf', '--scoreCutoffFilter',
					dest = "scoreCutoffFilter",
					action = "store",
					default = "",
					type = check_empty_or_integer,
					help = "Minimum score supporting a gene rearrangement in order to be kept during the analysis (intermediate filtering step to speed up the analysis) [default='empty'; will consider 2 for seqDepth = low, 5 for int, and 10 for high].")

parser.add_argument('-scsr', '--scoreCutoffCSR',
					dest = "scoreCutoffCSR",
					action = "store",
					default = "",
					type = check_empty_or_integer,
					help = "Minimum score supporting a CSR rearrangement in order to be considered as high confidence [default='empty'; will consider 5 for seqDepth = low, 10 for int, and 15 for high].")

parser.add_argument('-rop', '--reportOnlyProductive',
					dest = "reportOnlyProductive",
					action = "store",
					default = "no",
					choices = ['no', 'oof', 'yes'],
					help = "Report only productive rearrangements in the 'output_filtered' file [no/oof/yes, defaul=no]. 'no' = report all rearrangements identified. 'oof' means out-of-frame and is used to filter out as unproductive only those rearrangements with an out-of-frame junction or, in other words, to report both productive rearrangements and in-frame rearrangements that are unproductive due to stop codons. 'yes' = report only productive rearrangements.")

# Oncogenic rearrangements (i.e., translocations, etc.):
parser.add_argument('-ror', '--runOncogenicRearrangements',
					dest = "runOncogenicRearrangements",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Run the analysis of oncogenic IG/TCR rearrangements [yes/no, default=yes].") 

parser.add_argument('-roor', '--runOnlyOncogenicRearrangements',
					dest = "runOnlyOncogenicRearrangements",
					action = "store",
					default = "no",
					choices = ['no', 'yes'],
					help = "Run only the analysis of oncogenic IG/TCR rearrangements [yes/no, default=no].") 

parser.add_argument('-mqOnco', '--mappingQualityOncoIg',
					dest = "mapqOnco",
					action = "store",
					default = "0",
					type = int,
					help = "Mapping quality cut off to filter out reads when analyzing oncogenic IG/TCR rearrangements [default=0].") 

parser.add_argument('-mntonco', '--minNumberReadsTumorOncoIg', 
					dest = "mntonco",
					action = "store",
					default = "5",
					type = int,
					help = "Minimum score supporting an oncogenic IG/TCR rearrangement in order to be annotated [default=5].")

parser.add_argument('-mntoncoPass', '--minNumberReadsTumorOncoIgPass', 
					dest = "mntoncoPass",
					action = "store",
					default = "",
					type = check_empty_or_integer,
					help = "Minimum score supporting an oncogenic IG/TCR rearrangement in order to be considered as high confidence [default='empty'; will consider 6 for seqDepth = low, 10 for int, and 15 for high].")

parser.add_argument('-vafOnco', '--vafOncoIgPass', 
					dest = "vafOnco",
					action = "store",
					default = "0.05",
					type = float,
					help = "Minimum VAF of an oncogenic IG/TCR rearrangement in order to be considered as high confidence [range: 0-1; default=0.05].")

parser.add_argument('-mnnonco', '--maxNumberReadsNormalOncoIg', 
					dest = "mnnonco",
					action = "store",
					default = "2",
					type = int,
					help = "Maximum number of reads supporting an oncogenic IG/TCR rearrangement in the normal sample in order to be considered as high confidence [default=2].")

parser.add_argument('-mncPoN', '--maxNumberCountInPoN', 
					dest = "mncPoN",
					action = "store",
					default = "2",
					type = int,
					help = "Maximum number of count in panel of normals (PoN) in order to be considered as high confidence [default=2].")

parser.add_argument('-gOnco', '--genesOncoIg', 
					dest = "genesOncoIg",
					action = "store",
					default = "protein_coding_canonical",
					choices = ['all', 'protein_coding', 'protein_coding_canonical'],
					help = "Genes to be annotated based on proximity to the oncogenic IG/TCR rearrangement breakpoints. All genes, only protein coding genes, or only canonical portein coding transcripts. For hg19 reference, protein_coding_canonical is not supported and it is treated as protein_coding. [all/protein_coding/protein_coding_canonical, default=protein_coding_canonical].")

parser.add_argument('-cgOnco', '--customGenesOncoIg', 
					dest = "customGenesOncoIg",
					action = "store",
					default = "",
					help = "Comma-separated list of genes to be annotated with higher priority on the non-IG/TCR breakpoint if they are found within '-gOncoDist' of the breakpoint [default=''].")

parser.add_argument('-gOncoDist', '--genesOncoIgDistance',
					dest = "genesOncoIgDistance",
					action = "store",
					default = "250000",
					type = int,
					help = "Maximum distance in base pairs from the non-IG/TCR breakpoint to the closest gene to annotate it [default=250000].")

parser.add_argument('-cgOncoDist', '--customGenesOncoIgDistance',
					dest = "customGenesOncoIgDistance",
					action = "store",
					default = "500000",
					type = int,
					help = "For genes provided in -cgOnco, maximum distance in base pairs from the non-IG/TCR breakpoint to the closest gene to annotate it [default=500000].")

# Purity calculation:
parser.add_argument('-ep', '--estimatePurity', 
					dest = "estimatePurity",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Estimate purity [no/yes, default=yes]. If specified, the purity is estimated based on the IG/TCR rearrangements and reported in the output. It does not effect the scores and internal cutoffs.") 

parser.add_argument('-epc', '--estimatePurityCoverage', 
					dest = "estimatePurityCoverage",
					action = "store",
					default = "no",
					choices = ['no', 'yes', 'igh'],
					help = "Count gene rearrangements when estimating purity based on drop of coverage even if IgCaller has not called the rearrangement [no/yes/igh, default=no]. 'igh' means only applied to IGH locus.") 

parser.add_argument('-scp', '--scoreCutoffPurity',
					dest = "scoreCutoffPurity",
					action = "store",
					default = "",
					type = check_empty_or_integer,
					help = "Minimum score supporting a rearrangement in order to be considered during purity calculation [default='empty'; same as 'scoreCutoff'].")

parser.add_argument('-ppc', '--plotPurityCoverage',
					dest = "plotPurityCoverage",
					action = "store",
					default = "yes",
					choices = ['no', 'yes'],
					help = "Plot coverage along J genes to visually evaluate coverage estimations [no/yes, default='yes'].")

# Samtools-related arguments:
parser.add_argument('-ptsam', '--pathToSamtools',
					dest = "pathToSamtools",
					action = "store",
					default = "",
					help = "Path to the directory where samtools is installed. No need to specify it if samtools is found in 'PATH' [default = 'empty', assuming it is in 'PATH'].") 

parser.add_argument('-@', '--threadsForSamtools', 
					dest = "threadsForSamtools",
					action = "store",
					default = "1",
					type = int,
					help = "Maximum number of threads used for samtools [default=1].")

options = parser.parse_args()

# Starting:
startTime = datetime.datetime.now()
print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller v2.0")
print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: starting run...")

# Prepare some variables and files:
print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: checking inputs...")

inputsFolder = options.inputsFolder
genomeVersion = options.genomeVersion
chrAnnot = options.chrAnnot
originalBamT = options.bamT
seq = options.seq
seqDepth = options.seqDepth
originalBamN = options.bamN
pairedMode = options.pairedMode
refGenome = options.refGenome
geneToAnalyze = options.geneToAnalyze
primer = options.primer
primerFasta = options.primerFasta
primerStringency = options.primerStringency
tumorPurity = options.tumorPurity
outputPath = options.outputPath
keepMiniIgBams = options.keepMiniIgBams
reportReadNames = options.reportReadNames
annotateSeq = options.annotateSeq
annotateSeqDB = options.annotateSeqDB
subsetsAnnotation = options.subsetsAnnotation
R110annotation = options.R110annotation
agsAnnotation = options.agsAnnotation
highSensitivity = options.highSensitivity
minimumNumberOfNucleotidesSoft = options.minimumNumberOfNucleotidesSoft
phaseReadsBasedOnMutations = options.phaseReadsBasedOnMutations
keepInsertSizeOnlyRearrangements = options.keepInsertSizeOnlyRearrangements
collapseSequences = options.collapseSequences
collapseSequencesSimilarity = float(options.collapseSequencesSimilarity)
shortV = options.shortV
mapq = str(options.mapq)
baseq = str(options.baseq)
depth = options.depth
altDepth = options.altDepth
vafCutoff = options.vafCutoff.rstrip(",").split(",")
vafCutoffNormal = options.vafCutoffNormal
scoreCutoff = int(options.scoreCutoff) if options.scoreCutoff != "" else 15 if seqDepth == "high" else 10 if seqDepth == "int" else 5
scoreCutoffFilter = int(options.scoreCutoffFilter) if options.scoreCutoffFilter != "" else 10 if seqDepth == "high" else 5 if seqDepth == "int" else 2
if scoreCutoffFilter > scoreCutoff: scoreCutoffFilter = scoreCutoff
scoreCutoffPurity = int(options.scoreCutoffPurity) if options.scoreCutoffPurity != "" else scoreCutoff
scoreCutoffCSR = int(options.scoreCutoffCSR) if options.scoreCutoffCSR != "" else 15 if seqDepth == "high" else 10 if seqDepth == "int" else 5
reportOnlyProductive = options.reportOnlyProductive
runOncogenicRearrangements = options.runOncogenicRearrangements
runOnlyOncogenicRearrangements = options.runOnlyOncogenicRearrangements
mapqOnco = str(options.mapqOnco)
mntonco = int(options.mntonco)
mntoncoPass = int(options.mntoncoPass) if options.mntoncoPass != "" else 15 if seqDepth == "high" else 10 if seqDepth == "int" else 6
vafOnco = options.vafOnco
mnnonco = options.mnnonco
mncPoN = options.mncPoN
genesOncoIg = options.genesOncoIg
customGenesOncoIg = options.customGenesOncoIg.split(",")
genesOncoIgDistance = options.genesOncoIgDistance
customGenesOncoIgDistance = options.customGenesOncoIgDistance
estimatePurity = options.estimatePurity
estimatePurityCoverage = options.estimatePurityCoverage
plotPurityCoverage = options.plotPurityCoverage
pathToSamtools = options.pathToSamtools if options.pathToSamtools == "" else options.pathToSamtools+"/"
threadsForSamtools = str(options.threadsForSamtools)

## Import IgCaller defined dictionaries and functions from IgCaller_reference_files:
sys.path.insert(0, inputsFolder)
from IgCaller_functions import *

## Check normal BAM or reference is available:
if originalBamN is None and refGenome is None:
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... normal BAM file and/or reference genome must be supplied using -N and -R, resepctively.")

## Check normal BAM and pairedMode specifications:
if originalBamN is not None and pairedMode is None:
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... pairedMode (-pm) must be specified when a normal BAM file is supplied.")

## Check pairedMode should be set to paired if reference is not available
if pairedMode == "unpaired" and refGenome is None:
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... a paired normal BAM file or the reference genome must be supplied.")

## Check refGenome should be set if seq is amplicon and annotateSeq is igblast
if seq == "amplicon" and refGenome is None and annotateSeq == "igblast":
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... reference genome must be supplied using -R when analyzing amplicon-based data (i.e., -seq amplicon) coupled with IgBLAST annotation (i.e., -a igblast).")

## Check IgBLAST database for TCR/all:
if annotateSeq == "igblast" and annotateSeqDB == "ogrdb" and geneToAnalyze in ["tcr", "both"]:
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... the 'ogrdb' can only be used to annotate IG genes. Please, use 'imgt' database to analyze TCR or IG+TCR. You can also analyze IG and TCR in independent runs, using 'ogrdb' for IG analyses.")

## Check collapse sequences:
if collapseSequencesSimilarity < 0 or collapseSequencesSimilarity > 1: 
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... -css / --collapseSequencesSimilarity should be a float between 0 and 1.")

## Check minimum number of nucleotides to consider split-reads:
if minimumNumberOfNucleotidesSoft <= 0: 
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... -mnns / --minimumNumberOfNucleotidesSoft should be an integer higher than 0.")

## Check primer for amplicon:
if seq == "amplicon" and primer is None:
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... primer has to be specified if '-seq amplicon' using the '-pr/--primer' argument.")
if primer == "Vseq" and primerFasta == "": 
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... '-prf/--primerFasta' must be specified if '-pr/--primer' is 'Vseq'.")

## Check tumor purity:
if tumorPurity < 0 or tumorPurity > 1: 
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... -p / --tumorPurity should be a float between 0 and 1.")

## Check VAF:
if len(vafCutoff) != 2: 
	sys.exit(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: error message... -vaf / --vafCutoff should be of the form '0.5,0.1'.")

## Note on TRBV30 and TRDV3 (- strand post J genes):
if geneToAnalyze in ["tcr", "both"]:
	print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: note... rearrangements involving the TRBV30 and TRDV3 genes may not be properly handled due to their peculiar orientation and location within the TRB and TRD loci.")

## hg19 or hg38 regions of the IG loci:
if chrAnnot == "ensembl": chrom = ""
else: chrom = "chr"
if genomeVersion == "hg19": 
	if geneToAnalyze == "ig": coordsToSubset = chrom+"2:89131589-90274600 "+chrom+"14:106052774-107288051 "+chrom+"22:22380000-23266000" # IGK IGH IGL
	elif geneToAnalyze == "tcr": coordsToSubset = chrom+"7:38292981-38407770 "+chrom+"7:141999017-142511084 "+chrom+"14:22089991-23014042" # TRG TRB TRA (TRD within TRA)
	else: coordsToSubset = chrom+"2:89131589-90274600 "+chrom+"7:38292981-38407770 "+chrom+"7:141999017-142511084 "+chrom+"14:22089991-23014042 "+chrom+"14:106052774-107288051 "+chrom+"22:22380000-23266000"
elif genomeVersion == "hg38": 
	if geneToAnalyze == "ig": coordsToSubset = chrom+"2:88822278-90245370 "+chrom+"14:105576937-106889844 "+chrom+"22:22016076-22932913" # IGK IGH IGL 
	elif geneToAnalyze == "tcr": coordsToSubset = chrom+"7:38230024-38378055 "+chrom+"7:142289011-142823287 "+chrom+"14:21611904-22562132" # TRG TRB TRA (TRD within TRA: 14:21914138-22479614)
	else: coordsToSubset = chrom+"2:88822278-90245370 "+chrom+"7:38230024-38378055 "+chrom+"7:142289011-142823287 "+chrom+"14:21611904-22562132 "+chrom+"14:105576937-106889844 "+chrom+"22:22016076-22932913"

## Output folder:
if outputPath is None:  wkDir = originalBamT.split("/")[-1].replace(".bam", "_IgCaller")
else: wkDir = outputPath+"/"+originalBamT.split("/")[-1].replace(".bam", "_IgCaller")
if not os.path.exists(wkDir): os.mkdir(wkDir)
if not os.path.exists(wkDir+"/tmp"): os.mkdir(wkDir+"/tmp")
errLogMpileup = wkDir+"/tmp/errLogMpileup.txt"

## Create mini IG-bam for tumor and normal (if available):
print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: creating mini BAM files...")
bamT = wkDir+"/"+originalBamT.split("/")[-1]
comms = pathToSamtools+"samtools view -h -P -F 1024 -b "+originalBamT+" "+coordsToSubset+" | "+pathToSamtools+"samtools sort -@ "+threadsForSamtools+" -o "+bamT  # -F 1024 = read is PCR or optical duplicate
subprocess.call(comms, shell=True)
comms = pathToSamtools+"samtools index -@ "+threadsForSamtools+" "+bamT
subprocess.call(comms, shell=True)
bamN = None
miniBamN = None
if originalBamN is not None:
	bamN = wkDir+"/"+originalBamN.split("/")[-1]
	comms = pathToSamtools+"samtools view -h -P -F 1024 -b "+originalBamN+" "+coordsToSubset+" | "+pathToSamtools+"samtools sort -@ "+threadsForSamtools+" -o "+bamN
	subprocess.call(comms, shell=True)
	comms = pathToSamtools+"samtools index -@ "+threadsForSamtools+" "+bamN 
	subprocess.call(comms, shell=True)

## Main output file:
filterOutputFile = wkDir+"/"+originalBamT.split("/")[-1].replace(".bam", "_output_filtered.tsv")
SUMM = open(filterOutputFile, "w")
header = "Analysis\tAnnotation\tMechanism\tScore\tMQ\tNum_reads\tV_gene_phase_info\tV_gene_pct_identity_to_germline\tLength_considered_identity\tFunctionality\tJunction_amino_acid_sequence\tSequence"+("" if reportReadNames == "no" else "\tRead_names")
SUMM.write(header+"\n")

# Iterate over each IG/TCR locus:
listGenes = ["IGH", "IGK", "IGL", "CSR"] if geneToAnalyze == "ig" else ["TRA", "TRB", "TRD", "TRG"] if geneToAnalyze == "tcr" else ["IGH", "IGK", "IGL", "CSR", "TRA", "TRB", "TRD", "TRG"] 	

if runOnlyOncogenicRearrangements == "no":	
	
	for GENE in listGenes:
		
		print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: analyzing %s..." %GENE)
		
		# 1) Get general information:
		chromGene, coordsToSubsetLocus, bedFile, Dseqs, germline_db_J, germline_db_D, germline_db_V, snps_file = getGeneralInfo(GENE, chrom, genomeVersion, inputsFolder, chrAnnot, annotateSeqDB)

		# 2) Create mini IG-locus-specific-BAM:
		miniBamT = wkDir+"/tmp/"+bamT.split("/")[-1].replace(".bam", "_miniBam.bam")
		comms = pathToSamtools+"samtools view -@ "+threadsForSamtools+" -h -q "+mapq+" -b "+bamT+" "+coordsToSubsetLocus+" > "+miniBamT
		subprocess.call(comms, shell=True)
		comms = pathToSamtools+"samtools index -@ "+threadsForSamtools+" "+miniBamT
		subprocess.call(comms, shell=True)
		
		miniSamT = wkDir+"/tmp/"+bamT.split("/")[-1].replace(".bam", "_miniSam.sam")
		comms = pathToSamtools+"samtools view -@ "+threadsForSamtools+" -q "+mapq+" "+bamT+" "+coordsToSubsetLocus+" > "+miniSamT
		subprocess.call(comms, shell=True)
		
		if bamN is not None and pairedMode == "paired":
			miniBamN = wkDir+"/tmp/"+bamN.split("/")[-1].replace(".bam", "_miniBam.bam")
			comms = pathToSamtools+"samtools view -@ "+threadsForSamtools+" -h -q "+mapq+" -b "+bamN+" -L "+bedFile+" > "+ miniBamN
			subprocess.call(comms, shell=True)
			comms = pathToSamtools+"samtools index -@ "+threadsForSamtools+" "+miniBamN 
			subprocess.call(comms, shell=True)

		# 3) Convert SAM file to annotated table and write to disc:
		## Take samfile, get columns of interest and anotate reads with large insert size (as insertSize) and split/soft clipped (as split) 
		annot_table = miniSamT.replace(".sam", "_splitinsert.tsv")
		store = convertSamToAnnotatedTable(miniSamT, chromGene, GENE, minimumNumberOfNucleotidesSoft)
		ANNOT_TABLE = open(annot_table, "w")
		for read, data in store.items(): ANNOT_TABLE.write("%s\n" %"\t".join([str(x) for x in data]))
		ANNOT_TABLE.close()
		
		# 4) Find the J and V genes corresponding to each split/insert size position:
		JV_list = findJandVgenes(annot_table, bedFile, GENE, genomeVersion)
		annot_table_JV = miniSamT.replace(".sam", "_splitinsert_VJ.tsv")
		ANNOT_TABLE_JV = open(annot_table_JV, "w")
		for i in JV_list: ANNOT_TABLE_JV.write(i)
		ANNOT_TABLE_JV.close()
		
		# 5) Find combinations of J-V:
		l = findCombinationsJandV(annot_table_JV, GENE)

		# 6) Assign positions/breaks to each J and V pairs:
		VJ_positions, data, pos = assignPositionsToJandV(l, annot_table_JV, seq, GENE)

		if GENE != "CSR":
			# 7) Append to list V,J positions and number of occurrences:
			information = addPositionsAndOccurrences(GENE, pos, bedFile, shortV, data)
			
			# 8) Clean positions and occurrences:
			information = cleanPositionsAndOccurrences(GENE, bedFile, information, highSensitivity, seq)

			# 9) Add readnames:
			information = addReadNames(GENE, information, annot_table_JV)

			# 10) Get J and V sequences:
			information = getJandVsequences("first", seq, phaseReadsBasedOnMutations, information, annot_table_JV, GENE, refGenome, snps_file, baseq, chromGene, bamN, pairedMode, miniBamT, miniBamN, depth, altDepth, tumorPurity, vafCutoff, vafCutoffNormal, pathToSamtools, threadsForSamtools, errLogMpileup)

			# 11) Get D sequences (IGH/TRB/TRD = N-D-N, IGK/IGL/TRA/TRG = N):
			information = getDsequence(information, annot_table_JV, GENE, Dseqs, minimumNumberOfNucleotidesSoft, seq, bedFile, refGenome, miniBamT, pathToSamtools, errLogMpileup)

			# 12) Remove low support rearrangements and adjust insertSize only rearrangements:
			information = removeLowSupportRearrangements(information, tumorPurity, scoreCutoffFilter, keepInsertSizeOnlyRearrangements, annot_table_JV, seqDepth)
			
			# 13) Re-get J and V sequences:
			## second round: to phase reads based on mutations
			## third round: to get final sequence based on all reads assigned to each rearrangement
			information = getJandVsequences("second", seq, phaseReadsBasedOnMutations, information, annot_table_JV, GENE, refGenome, snps_file, baseq, chromGene, bamN, pairedMode, miniBamT, miniBamN, depth, altDepth, tumorPurity, vafCutoff, vafCutoffNormal, pathToSamtools, threadsForSamtools, errLogMpileup)
			information = getJandVsequences("third", seq, phaseReadsBasedOnMutations, information, annot_table_JV, GENE, refGenome, snps_file, baseq, chromGene, bamN, pairedMode, miniBamT, miniBamN, depth, altDepth, tumorPurity, vafCutoff, vafCutoffNormal, pathToSamtools, threadsForSamtools, errLogMpileup)

			# 14) Collapse rearrangements with similar nucleotide sequences:
			if collapseSequences == "yes": information = doCollapseSequences(information, collapseSequencesSimilarity, GENE)

			# 15) Check homology and functionality (productive/unproductive):
			information = checkHomologyAndFunctionality(information, GENE) if annotateSeq == "builtin" else igBlastAnnotate(information, GENE, wkDir, inputsFolder, germline_db_J, germline_db_D, germline_db_V, seq, primer, primerStringency, primerFasta, agsAnnotation)

			# 16) Add mapping quality and calculate score:
			information = addMapQualAndScore(information, miniBamT, tumorPurity, pathToSamtools, threadsForSamtools)

			# 17) Adjust read names and update sequence of partial rearrangements:
			information = adjustReadNamesAndPartialRearrangements(information, GENE)
			
			# 18) Annotate CLL stereotyped subsets and IGLV3-21 R110:
			if GENE == "IGH" and subsetsAnnotation != "no": information = annotateCLLsubsets(information, subsetsAnnotation)
			if GENE == "IGL" and R110annotation == "yes": information = annotateR110mutation(information)
			
			# 19) Pre-defined filter:
			trip = predefinedFilter(information, seq, seqDepth, reportOnlyProductive, scoreCutoff, genomeVersion, collapseSequencesSimilarity)
			
			# 20) Save output and clean:
			Vseq = open(bamT.replace(".bam", "_output_"+GENE+".tsv"), "w")
			Vseq.write("Genes\tMechanism\tN_split\tN_insertSize\tStart_J\tEnd_J\tN_split_rescued_J\tStart_V\tEnd_V\tN_split_rescued_V\tN_phased_rescued\tSeq_J\tSeq_D\tSeq_V\tSeq_V_normal\tSeq\tV_gene_pct_identity_to_germline\tLength_considered_identity\tFunctionality\tJunction_amino_acid_sequence\tScore\tMQ\tV_gene_phase_info"+("" if reportReadNames == "no" else "\tRead_names")+"\n")
			if len(information) > 0:
				indxs = [21]+list(range(1,15))+list(range(16,20))+[20]+list(range(22,24))+[15]
				if reportReadNames == "yes": indxs.append(24)
				Vseq.write("\n".join(['\t'.join(map(str, (item[i] for i in indxs))) for item in information])+"\n")
			Vseq.close()
			
			if len(trip) != 0:
				indxs = [0,21,22,24,14,16,17,18,19,15]
				if reportReadNames == "yes": indxs.append(23)
				SUMM.write("\n".join([GENE+"\t"+trip[item][20]+"\t"+'\t'.join(map(str, map(trip[item].__getitem__, indxs))) for item in trip])+"\n")
			else:
				SUMM.write(GENE+"\tNo rearrangement found"+"\tNA"*(10 if reportReadNames == "no" else 11)+"\n")
		
		elif GENE == "CSR":
			# 21) Study coverage around CSR and return info:
			class_switch, class_switch_filt, reductionMeans = classSwitchAnalysis(wkDir, data, annot_table_JV, bedFile, baseq, chromGene, bamT, bamN, pathToSamtools, tumorPurity, seq, scoreCutoffCSR, errLogMpileup)

			Vseq = open(bamT.replace(".bam", "_output_"+GENE+".tsv"), "w")
			Vseq.write("Genes\tMechanism\tScore\tMQ\tNum_reads\tAdjusted_mean_pre_break\tAdjusted_mean_post_break\tP_value\tPct_reduction_adjusted_means"+("" if reportReadNames == "no" else "\tRead_names")+"\n")
			if len(class_switch) > 0:
				indxs = [0,1,2,3,4,5,6,7,8]
				if reportReadNames == "yes": indxs.append(9)
				Vseq.write("\n".join(['\t'.join(map(str, (item[i] for i in indxs))) for item in class_switch])+"\n")
			Vseq.close()
			
			if len(class_switch_filt) == 0:
				SUMM.write("CSR\tIGHM\tNo CSR found"+"\tNA"*(9 if reportReadNames == "no" else 10)+"\n")
			else:
				class_switch_filt = class_switch_filt[reductionMeans.index(max(reductionMeans))] # keep only the one with highest reduction/score
				SUMM.write("\t".join(["CSR", class_switch_filt[0], class_switch_filt[1], str(class_switch_filt[2]), class_switch_filt[3], str(class_switch_filt[4])]+["NA"]*6)+("" if reportReadNames == "no" else "\t"+class_switch_filt[9])+"\n")
		
		# 22) Clean intermediate files:
		subprocess.call("rm "+wkDir+"/tmp/*", shell=True)

# 23) Genome-wide IG/TCR translocations:
if runOncogenicRearrangements == "yes":
	print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: analyzing genome-wide "+("IG" if geneToAnalyze == "ig" else "TCR" if geneToAnalyze == "tcr" else "IG/TCR")+" rearrangements...")
	translocationsALL, translocationsPASS = getIgTranslocations(wkDir, genomeVersion, inputsFolder, pathToSamtools, threadsForSamtools, coordsToSubset, bamT, bamN, pairedMode, chrom, geneToAnalyze, tumorPurity, mntonco, mntoncoPass, vafOnco, mnnonco, mapqOnco, mncPoN, genesOncoIg, customGenesOncoIg, genesOncoIgDistance, customGenesOncoIgDistance, reportReadNames, errLogMpileup)

	Vseq = open(bamT.replace(".bam", "_output_oncogenic_rearrangements.tsv"), "w")
	Vseq.write("\n".join(translocationsALL)+"\n")
	Vseq.close()

	if len(translocationsPASS) > 0: SUMM.write("\n".join(translocationsPASS)+"\n")
	else: SUMM.write("Oncogenic "+("IG" if geneToAnalyze == "ig" else "TCR" if geneToAnalyze == "tcr" else "IG/TCR")+" rearrangement\tNo rearrangements found"+"\tNA"*(10 if reportReadNames == "no" else 11)+"\n")

	subprocess.call("rm "+wkDir+"/tmp/*", shell=True)

SUMM.close()

# 24) Coverage-based tumor cell content (ie purity):
if estimatePurity == "yes" and runOnlyOncogenicRearrangements == "no":
	print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: calculating purity...")
	if bamN is None: print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: warning message... purity estimates are more accurately calculated when using a normal BAM file (either paired or unpaired) as a reference.")
	getPurity(wkDir, seq, chrom, genomeVersion, inputsFolder, chrAnnot, filterOutputFile, listGenes, estimatePurityCoverage, bamT, bamN, seqDepth, pathToSamtools, mapq, scoreCutoffPurity, plotPurityCoverage, reportReadNames, errLogMpileup)

# 25) Clean tmp folder, mini IG bam files - if specified - and close:
subprocess.call("rm -r "+wkDir+"/tmp" , shell=True)

if keepMiniIgBams != "yes":
	print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: cleaning mini IG bam files...")
	comms = "rm "+wkDir+"/*.bam "+wkDir+"/*.bam.bai"  
	subprocess.call(comms, shell=True)

endTime = datetime.datetime.now()
execTime = str(endTime-startTime)
print(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+" - IgCaller: done. Execution time: "+execTime)
